project:
  type: website

website:
  google-analytics: "UA-367916546"
  title: "Fl√°via E. Rius"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/flaviaerius
      - icon: twitter
        href: https://twitter.com/flaviaerius
format:
  html:
    theme: flatly
    css: styles.css
    
comments:
  giscus: 
    repo: flaviaerius/blog_quarto



